### ISSUE TITLE
Haplotype counting

### ISSUE THREAD

**Issue by Eduardo-Auer** [isglobal-brge/SNPassoc#11]
Hello,

I am using `haplo.em()` and `haplo.group()` functions to obtain haplotype frequencies, and I need haplotype counts from these reconstructed haplotypes to compare with other populations (fisher exact test or chi-squared test). I have searched for these counts in these functions and have yet to be successful. 

Is there a way to obtain reconstructed haplotype counting?

**Comment by isglobal-brge** [comment]
Hi,

these functions belongs to haplo.stats R package. Maybe you can contact the authors who wrote these functions. 

https://cran.r-project.org/web/packages/haplo.stats/index.html

Best
Juan
