### ISSUE TITLE
getNiceTable function issue

### ISSUE THREAD

**Issue by nampharmd** [isglobal-brge/SNPassoc#2]
Hello! I want to see if the getNiceTable function working?

I got the following message when running the code:

> library(xtable)
> out <- getNiceTable(ans[c("rs1422993", "rs184448")])
Error in getNiceTable(ans[c("rs1422993", "rs184448")]) : 
  could not find function "getNiceTable"

Is there a workaround to extract the statistic (p-value, OR, etc..) for SNP of interest on each mode of inheritable into a table format for publication? 

Many thanks!

**Comment by isglobal-brge** [comment]
Please, install the version that is available in GitHub

library(devtools)
install_github("isglobal-brge/SNPassoc")

I will add this feature to CRAN in a new release

Thanks
