### ISSUE TITLE
Updated version?

### ISSUE THREAD

**Issue by Lidija0710** [isglobal-brge/SNPassoc#3]
Hi! Is there an updated version of this SNPassoc coming soon? I get this error:

install.packages("SNPassoc")
Warning in install.packages :
  package ‘SNPassoc’ is not available for this version of R

thanks!

**Comment by isglobal-brge** [comment]
Hi Lidija, 

there is not ... I did not receive anything from CRAN saying that SNPassoc did not pass their checks. Now, I am fixing the bugs (nothing related to SNPassoc functions but with the new R vesion).

Meanwhile, you can install our package from GitHub using

library(devtools)
install_githug("isglobal-brge/SNPassoc")

Thanks for your comment
Juan

**Comment by isglobal-brge** [comment]
Since few weks on CRAN
