### ISSUE TITLE
No p-value returned for some data

### ISSUE THREAD

**Issue by MboiTui** [isglobal-brge/SNPassoc#9]
Hello,

I am pretty new to association tests so please forgive me if I am misunderstanding something.

I am running association tests for ~14,000 SNPs for phenotypic sex.

All SNPs identified as sex-linked with other methods appear to be significantly associated with sex (as expected).

Now I want to plot significance along my linkage maps, but for some SNPs the WGassociation and association functions do not return a pvalue. See contingency table below as an example

```
SNP: X25207_47  adjusted by: 
              1    %  2    % OR lower upper p-value  AIC
Codominant                                              
A/A          15 78.9 15 78.9  1                     56.7
A/C           4 21.1  4 21.1  1  0.21  4.76             
log-Additive                                            
0,1,2        19 50.0 19 50.0  1  0.21  4.76         56.7
```

Is that normal behaviour for these functions, and if so why? 

Once again, apologies if I am missing something obvious. I tried reading the vignette and manual but didn't find an answer

**Comment by isglobal-brge** [comment]
You can see that for this SNP the OR is exactly equal to 1 ... the p-value cannot be computed -- you have the same number of individuals at each cell for cases and controls

**Comment by MboiTui** [comment]
Thank you for the clarification, and apologies for my lack of understanding of the underlying statistics
